<?php

namespace App\Services;

use Illuminate\Support\Facades\Http;
use Illuminate\Support\Facades\Log;

class GeminiFileSearch
{
    protected $baseUrl = 'https://generativelanguage.googleapis.com/v1beta';
    protected $apiKey;

    public function __construct()
    {
        $this->apiKey = env('GEMINI_API_KEY');
    }

    /**
     * 1. CHAT: Send a message using the File Search Store (RAG)
     */
    public function chatWithStore($storeName, $userMessage)
    {
        // Use Gemini 2.5 Flash for speed and cost-efficiency
        $model = 'models/gemini-2.5-flash';

        $url = "{$this->baseUrl}/{$model}:generateContent?key={$this->apiKey}";

        $strictInstruction = "Answer in Malay. Provide a concise answer in a numbered list. DO NOT PROVIDE EXPLANATIONS FOR EACH ITEM. START THE ANSWER IMMEDIATELY WITH NUMBER 1. DO NOT PROVIDE ANY INTRODUCTION OR PREAMBLE.";
        
        // Combine the strict instruction with the user's question
        $combinedPrompt = $strictInstruction . " Pertanyaan pengguna: " . $userMessage;

        // Define max output tokens (This is correct to control length)
         $maxTokens = 500;

        $body = [
            'contents' => [
                [
                    'role' => 'user', 
                    'parts' => [['text' => $combinedPrompt]]
                ]
            ],

            'generationConfig' => [
                'maxOutputTokens' => $maxTokens, 
            ],
            
            'tools' => [
                [
                    'file_search' => [ 
                    // Use snake_case for the store name list and wrap $storeName in an array
                        'file_search_store_names' => [$storeName] 
                    ]
                ]
            ]
        ];

        $response = Http::withHeaders(['Content-Type' => 'application/json'])
            ->post($url, $body);

        if ($response->failed()) {
            Log::error('Gemini Final RAG Status', [
                'status' => $response->status(),
                'body' => $response->json(),
                'store_id_used' => $storeName, // Log the actual ID being sent
            ]);
            // Fallback or throw error
            return "Respon RAG gagal diterima.";
        }

        $rawText = $response->json()['candidates'][0]['content']['parts'][0]['text'] ?? '';

        // --- START: Response Reformatting/Cleanup ---
        
        // 1. Remove unnecessary leading/trailing whitespace (spaces, newlines)
        $cleanText = trim($rawText);

        // 2. Remove common prefixes sometimes generated by RAG/AI models
        //    e.g., "The documents state:", "Jawapan:", "Ringkasan:"
        $prefixesToRemove = [
            'Jawapan:', 'Ringkasan:', 'Di sini ringkasan:', 
            'Here is a summary:', 'Based on the documents:'
        ];
        
        foreach ($prefixesToRemove as $prefix) {
            // Use case-insensitive search and remove only if it appears at the start
            if (stripos($cleanText, $prefix) === 0) {
                $cleanText = substr($cleanText, strlen($prefix));
                $cleanText = trim($cleanText); // Re-trim after removal
                break; // Stop checking after the first match
            }
        }
        
        // 3. Simple final check if text is empty after cleaning (should not happen often)
        if (empty($cleanText)) {
            return 'Respon kosong';
        }
        
        return $cleanText;
    }

    /**
     * 2. UPLOAD: Uploads a file AND links it to a specific Store
     */
    public function uploadAndIndexFile($storeName, $filePath, $mimeType)
    {
        $fileSize = filesize($filePath);
        $displayName = basename($filePath);

        // --- A. Initial Resumable Upload Request ---
        // We ask Google for a unique upload URL
        $initResponse = Http::withHeaders([
            'X-Goog-Upload-Protocol' => 'resumable',
            'X-Goog-Upload-Command' => 'start',
            'X-Goog-Upload-Header-Content-Length' => $fileSize,
            'X-Goog-Upload-Header-Content-Type' => $mimeType,
            'Content-Type' => 'application/json',
        ])->post("https://generativelanguage.googleapis.com/upload/v1beta/files?key={$this->apiKey}", [
            'file' => ['displayName' => $displayName]
        ]);

        if ($initResponse->failed()) {
            Log::error('Gemini Upload Init Failed', $initResponse->json());
            throw new \Exception("Failed to initialize upload.");
        }

        $uploadUrl = $initResponse->header('X-Goog-Upload-URL');

        // --- B. Perform the actual byte upload ---
        $fileContent = file_get_contents($filePath);
        
        $uploadResponse = Http::withHeaders([
            'Content-Length' => $fileSize,
            'X-Goog-Upload-Offset' => '0',
            'X-Goog-Upload-Command' => 'upload, finalize',
        ])->withBody($fileContent, $mimeType)->post($uploadUrl);

        if ($uploadResponse->failed()) {
            Log::error('Gemini Binary Upload Failed', $uploadResponse->json());
            throw new \Exception("Failed to upload file bytes.");
        }

        $uploadedFile = $uploadResponse->json()['file']; // We get back the file object

        // --- C. Link the file to your Vector Store ---
        // This step actually performs the RAG indexing
        $importUrl = "{$this->baseUrl}/{$storeName}:importFile?key={$this->apiKey}";
        
        $linkResponse = Http::post($importUrl, [
            'file_name' => $uploadedFile['name'] // e.g. "files/abc123xyz"
        ]);
        
        $operationName = $linkResponse->json()['name']; // e.g., "operations/importFile-12345"
        if (!$operationName) {
            throw new \Exception("Failed to initiate indexing operation.");
        }

        // --- D. Wait for Indexing to Complete (LRO Polling) ---
        $maxAttempts = 30; // 30 attempts * 10 seconds = 5 minutes total wait
        $delaySeconds = 10; 

        for ($i = 0; $i < $maxAttempts; $i++) {
            sleep($delaySeconds); // Pause before checking
            
            $statusUrl = "{$this->baseUrl}/{$operationName}?key={$this->apiKey}";
            $statusResponse = Http::get($statusUrl);

            if ($statusResponse->failed() || ($statusResponse->json()['error'] ?? false)) {
                Log::error("RAG Indexing Failed: ", $statusResponse->json());
                throw new \Exception("RAG Indexing failed during operation check.");
            }
            
            // Check for "done": true
            if (($statusResponse->json()['done'] ?? false) === true) {
                Log::info("RAG Indexing complete for file: " . $uploadedFile['displayName']);
                return $statusResponse->json(); // Success!
            }
        }

        // If the loop finishes, it timed out
        throw new \Exception("RAG Indexing timed out after " . ($maxAttempts * $delaySeconds) . " seconds.");

        return $linkResponse->json();
    }

    /**
     * 3. SETUP: Create a new Store (Run this once to get your ID)
     */
    public function createStore($displayName = 'LMS Global Store')
    {
        $response = Http::post("{$this->baseUrl}/fileSearchStores?key={$this->apiKey}", [
            'displayName' => $displayName
        ]);
        
        return $response->json()['name'] ?? null; // Returns "fileSearchStores/xxxxxx"
    }

    public function listFiles()
    {
        // This endpoint lists all files owned by your API key
        $url = "{$this->baseUrl}/files?key={$this->apiKey}&pageSize=100";

        $response = Http::get($url);

        if ($response->failed()) {
            Log::error('Gemini List Files Failed', $response->json());
            return [];
        }

        // map() to format the data nicely for the frontend
        $files = collect($response->json()['files'] ?? [])->map(function ($file) {
            return [
                'name' => $file['name'], // e.g., "files/abc123xyz"
                'display_name' => $file['displayName'], // e.g., "Physics_Chapter_1.pdf"
                'mime_type' => $file['mimeType'],
                'size_bytes' => $file['sizeBytes'],
                'created_at' => \Carbon\Carbon::parse($file['createTime'])->diffForHumans(),
                'state' => $file['state'] // e.g., "ACTIVE" or "PROCESSING"
            ];
        });

        return $files;
    }

    /**
     * 5. DELETE: Remove a file from the knowledge base
     */
    public function deleteFile($fileName)
    {
        $url = "{$this->baseUrl}/{$fileName}?key={$this->apiKey}";
        return Http::delete($url)->successful();
    }
}